replicaCount: 1

image:
  repository: osrf/ros
  tag: humble-desktop
  pullPolicy: IfNotPresent

loadGenerator:
  messageRate: 10
  scriptPath: load_sim.py

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

containerPort: 8080