apiVersion: v2
name: ros2-monolithic
description: A Helm chart for a monolithic ROS 2 demo (talker+listener & load simulator)
type: application
version: 0.2.2
appVersion: humble
keywords:
  - ros2
  - monolithic
  - robotics
maintainers:
  - name: Miguel-Angel-Mateo-Casali
    email: mmateo@cigip.upv.es
