replicaCount: 1

image:
  repository: osrf/ros
  tag: humble-desktop
  pullPolicy: IfNotPresent

loadSimulator:
  messageRate: 10
  scriptPath: load_sim.py

api:
  port: 5000

loadGenerator:
  messageRate: 10
  scriptPath: load_sim.py

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000

containerPort: 5000

metrics:
  enabled: true
  port: 9090

nameOverride: ""
fullnameOverride: ""
