apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dynamic-loader.fullname" . }}
  labels:
    {{- include "dynamic-loader.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "dynamic-loader.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "dynamic-loader.name" . }}
    spec:
      containers:
        - name: dynamic-host
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /app
          env:
            - name: PORT
              value: "{{ .Values.api.port }}"
          command:
            - /ros_entrypoint.sh
            - bash
            - -lc
            - |
             apt-get update && \
             apt-get install -y python3-pip && \
             python3 -m pip install --no-cache-dir fastapi uvicorn && \
             python3 -m uvicorn server:app --host 0.0.0.0 --port $PORT
          ports:
            - containerPort: {{ .Values.api.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: app-code
              mountPath: /app
            - name: modules
              mountPath: /modules
      volumes:
        - name: app-code
          configMap:
            name: {{ include "dynamic-loader.fullname" . }}-code
        - name: modules
          emptyDir: {}