apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dynamic-loader.fullname" . }}
  labels:
    {{- include "dynamic-loader.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.metrics.port }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "dynamic-loader.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "dynamic-loader.name" . }}
    spec:
      containers:
        - name: dynamic-host
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /app
          env:
            - name: PORT
              value: "{{ .Values.api.port }}"
            - name: METRICS_PORT
              value: "{{ .Values.metrics.port }}"
          command:
            - /ros_entrypoint.sh
            - bash
            - -lc
            - |
              apt-get update && \
              apt-get install -y python3-pip && \
              python3 -m pip install --no-cache-dir fastapi uvicorn prometheus_client && \
              python3 /app/server.py
          ports:
            - containerPort: {{ .Values.api.port }}
            - containerPort: {{ .Values.metrics.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: app-code
              mountPath: /app/server.py
              subPath: server.py
            - name: modules
              mountPath: /modules
      volumes:
        - name: app-code
          configMap:
            name: {{ include "dynamic-loader.fullname" . }}-code
        - name: modules
          emptyDir: {}