apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dynamic-loader.fullname" . }}
  labels:
    {{- include "dynamic-loader.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "dynamic-loader.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "dynamic-loader.name" . }}
    spec:
      containers:
        - name: dynamic-host
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /ros_entrypoint.sh
            - python3
            - /app/server.py
          ports:
            - containerPort: {{ .Values.api.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: app-code
              mountPath: /app
            - name: modules
              mountPath: /modules
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.api.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.api.port }}
            initialDelaySeconds: 15
            periodSeconds: 20

      volumes:
        - name: app-code
          configMap:
            name: {{ include "dynamic-loader.fullname" . }}-code
        - name: modules
          emptyDir: {}