apiVersion: v1
kind: Service
metadata:
  name: {{ include "dynamic-loader.fullname" . }}
  labels:
    {{- include "dynamic-loader.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "dynamic-loader.name" . }}
  ports:
    - name: api
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}