image:
  repository: osrf/ros
  tag: humble-desktop
  pullPolicy: IfNotPresent

cloud:
  replicas: 1
  nodeSelector:
    kubernetes.io/hostname: cloud-node

edge:
  replicas: 1
  nodeSelector:
    kubernetes.io/hostname: edge-node

loadGenerator:
  messageRate: 10
  scriptPath: load_sim.py

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

containerPort: 8080

nameOverride: ""
fullnameOverride: ""
