replicaCount: 1

image:
  repository: osrf/ros
  tag: humble-desktop
  pullPolicy: IfNotPresent

cloud:
  replicas: 1

edge:
  replicas: 1

loadGenerator:
  messageRate: 10
  scriptPath: load_sim.py

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

containerPort: 8080

metrics:
  enabled: true
  port: 9090

# Optional name overrides
ameOverride: ""
fullnameOverride: ""