apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ros2-monolithic.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ros2-monolithic.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ros2-monolithic.name" . }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: robot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ros2", "launch", "my_robot_bringup", "monolith.launch.py"]
          resources: {{- toYaml .Values.resources | nindent 12 }}
