apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloud-edge.fullname" . }}-edge-processing
  labels:
    {{- include "cloud-edge.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.edge.replicas }}
  selector:
    matchLabels:
      app: edge-processing
  template:
    metadata:
      labels:
        app: edge-processing
    spec:
      containers:
        - name: processor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /ros_entrypoint.sh
            - ros2
            - run
            - demo_nodes_cpp
            - listener
          ports:
            - containerPort: {{ .Values.containerPort }}
        - name: load-generator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /ros_entrypoint.sh
            - python3
            - /scripts/{{ .Values.loadGenerator.scriptPath }}
          env:
            - name: MESSAGE_RATE
              value: "{{ .Values.loadGenerator.messageRate }}"
          volumeMounts:
            - name: load-sim
              mountPath: /scripts/{{ .Values.loadGenerator.scriptPath }}
              subPath: {{ .Values.loadGenerator.scriptPath }}
      volumes:
        - name: load-sim
          configMap:
            name: {{ include "cloud-edge.fullname" . }}-load-sim
