apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ros2-monolithic.fullname" . }}
  labels:
    {{- include "ros2-monolithic.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ros2-monolithic.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ros2-monolithic.name" . }}
    spec:
      containers:
        - name: ros-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /ros_entrypoint.sh
            - ros2
            - launch
            - demo_nodes_cpp
            - talker_listener.launch.py
          env:
            - name: MESSAGE_RATE
              value: "{{ .Values.loadSimulator.messageRate }}"
          ports:
            - containerPort: {{ .Values.containerPort }}

        - name: load-simulator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /ros_entrypoint.sh
            - python3
            - /scripts/{{ .Values.loadSimulator.scriptPath }}
          env:
            - name: MESSAGE_RATE
              value: "{{ .Values.loadSimulator.messageRate }}"
          volumeMounts:
            - name: load-sim
              mountPath: /scripts/{{ .Values.loadSimulator.scriptPath }}
              subPath: {{ .Values.loadSimulator.scriptPath }}

      volumes:
        - name: load-sim
          configMap:
            name: {{ include "ros2-monolithic.fullname" . }}-load-sim
