replicaCount: 1

image:
  repository: osrf/ros
  tag: humble-desktop
  pullPolicy: IfNotPresent

api:
  port: 5000

metrics:
  enabled: true
  port: 9090

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# opcionales
ameOverride: ""
fullnameOverride: ""