replicaCount: 1

image:
  repository: osrf/ros
  tag: humble-desktop
  pullPolicy: IfNotPresent

api:
  port: 5000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000

nameOverride: ""
fullnameOverride: ""
