apiVersion: v1
kind: Service
metadata:
  name: {{ include "ros2-monolithic.fullname" . }}
  labels:
    {{- include "ros2-monolithic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "ros2-monolithic.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
