# values.yaml para Dynamic Module Loading Pattern
# Sistema ROS 2 con capacidad de cargar módulos dinámicamente vía API

replicaCount: 1

image:
  repository: osrf/ros
  tag: humble-desktop
  pullPolicy: IfNotPresent

# Configuración ROS 2
ros:
  domainId: 42
  rmwImplementation: rmw_fastrtps_cpp

# Selector de nodo
nodeSelector:
  # Desplegar donde necesites
  kubernetes.io/hostname: kb2.cigip.upv.es
  # O en edge:
  # kubernetes.io/hostname: kb-edge01.cigip.upv.es

# API HTTP para carga dinámica
api:
  port: 5000
  enabled: true

# Base image con dependencias preinstaladas
# IMPORTANTE: En producción, crear una imagen custom con FastAPI ya instalado
baseImageCustom:
  enabled: false
  # Si enabled: true, usar:
  # repository: your-registry/ros2-dynamic-loader
  # tag: latest

# Recursos
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

# Servicio
service:
  type: ClusterIP
  port: 5000
  targetPort: 5000
  # Para exponer externamente:
  # type: NodePort
  # nodePort: 30500

# Persistencia (opcional, para mantener módulos entre reinicios)
persistence:
  enabled: false
  storageClass: ""
  size: 1Gi
  mountPath: /modules

# Seguridad
security:
  # En producción, habilitar validación de módulos
  validateModules: false
  allowedModuleNames: []
  # allowedModuleNames:
  #   - perception_module
  #   - navigation_module

nameOverride: ""
fullnameOverride: ""