apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ros2-microservices.fullname" . }}-load-sim
  labels:
    {{- include "ros2-microservices.labels" . | nindent 4 }}
data:
  load_sim.py: |
{{- nindent 4 .Values.config.loadSimScript }}