{{- if and .Values.talker.service.enabled (.Values.talker.service.ports) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ros2-microservices.fullname" . }}-talker
  labels:
    {{- include "ros2-microservices.labels" . | nindent 4 }}
spec:
  type: {{ .Values.talker.service.type | default "ClusterIP" }}
  selector:
    app: talker
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  {{- range .Values.talker.service.ports }}
    - name: {{ required "nombre de puerto requerido" .name }}
      port: {{ required "port requerido" .port }}
      targetPort: {{ required "targetPort requerido" .targetPort }}
      protocol: {{ .protocol | default "UDP" }}
  {{- end }}
{{- end }}
