apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ros2-microservices.fullname" . }}-talker
  labels:
    {{- include "ros2-microservices.labels" . | nindent 4 }}
    app: talker
    microservice: talker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: talker
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "ros2-microservices.labels" . | nindent 8 }}
        app: talker
        microservice: talker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      # POD-LEVEL security (NO root)
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

      nodeSelector:
        {{- toYaml .Values.talker.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.talker.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.talker.tolerations | nindent 8 }}

      containers:
        - name: talker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false

          command: ["/bin/bash","-lc"]
          args:
            - |
              source /opt/ros/humble/setup.bash
              echo "=== Talker Microservice Starting ==="
              echo "Domain ID: ${ROS_DOMAIN_ID}"
              ros2 run demo_nodes_cpp talker

          env:
            - name: ROS_DOMAIN_ID
              value: {{ .Values.commonEnv.ROS_DOMAIN_ID | quote }}
            - name: RMW_IMPLEMENTATION
              value: {{ .Values.commonEnv.RMW_IMPLEMENTATION | quote }}
            - name: ROS_LOCALHOST_ONLY
              value: {{ .Values.commonEnv.ROS_LOCALHOST_ONLY | quote }}

          resources:
            {{- toYaml .Values.resources.talker | nindent 12 }}
