apiVersion: v1
kind: Service
metadata:
  name: {{ include "ros2-microservices.fullname" . }}-talker
  labels:
    app.kubernetes.io/name: {{ include "ros2-microservices.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: talker
  ports:
    - port: {{ .Values.service.talker.port }}
      targetPort: {{ .Values.service.talker.targetPort }}
