apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloud-edge.fullname" . }}-fleet-manager
  labels:
    {{- include "cloud-edge.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.cloud.replicas }}
  selector:
    matchLabels:
      app: fleet-manager
  template:
    metadata:
      labels:
        app: fleet-manager
    spec:
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /ros_entrypoint.sh
            - ros2
            - run
            - demo_nodes_cpp
            - talker
          ports:
            - containerPort: {{ .Values.containerPort }}
