apiVersion: v1
kind: Service
metadata:
  name: fleet-manager
spec:
  selector:
    app: fleet-manager
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: edge-processing
spec:
  selector:
    app: edge-processing
  ports:
    - port: 8080
      targetPort: 8080
