apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-edge.fullname" . }}-fleet-manager
  labels:
    {{- include "cloud-edge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: fleet-manager
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-edge.fullname" . }}-edge-processing
  labels:
    {{- include "cloud-edge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: edge-processing
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
