apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ros2-microservices.fullname" . }}-load-sim
  labels:
    {{- include "ros2-microservices.labels" . | nindent 4 }}
data:
  {{ .Values.loadGenerator.scriptPath }}: |
    #!/usr/bin/env python3
    import os, time, rclpy
    from rclpy.node import Node
    from std_msgs.msg import String
    from prometheus_client import start_http_server, Gauge

    LATENCY = Gauge('ros2_latency_seconds', 'End-to-end latency in seconds')

    class LoadSim(Node):
        def __init__(self):
            super().__init__('bench_load')
            self.pub = self.create_publisher(String, 'chatter', 10)
            rate = float(os.getenv('MESSAGE_RATE', '10'))
            start_http_server(int(os.getenv('METRICS_PORT', '9090')))
            self.create_timer(1.0 / rate, self.cb)

        def cb(self):
            ts = time.time()
            msg = String()
            msg.data = str(ts)
            self.pub.publish(msg)

    def main():
        rclpy.init()
        node = LoadSim()
        try:
            rclpy.spin(node)
        finally:
            node.destroy_node()
            rclpy.shutdown()

    if __name__ == '__main__':
        main()