apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ros2-microservices.fullname" . }}-listener
  labels:
    {{- include "ros2-microservices.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.metrics.port }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: listener
  template:
    metadata:
      labels:
        app: listener
    spec:
      containers:
        - name: listener
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /ros_entrypoint.sh
            - python3
            - /scripts/listener.py
          env:
            - name: METRICS_PORT
              value: "{{ .Values.metrics.port }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
            - containerPort: {{ .Values.metrics.port }}
          volumeMounts:
            - name: listener-code
              mountPath: /scripts/listener.py
              subPath: listener.py
      volumes:
        - name: listener-code
          configMap:
            name: {{ include "ros2-microservices.fullname" . }}-listener-code