apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ros2-microservices.fullname" . }}-listener
  labels:
    app.kubernetes.io/name: {{ include "ros2-microservices.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: listener
  template:
    metadata:
      labels:
        app: listener
    spec:
      containers:
        - name: listener
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ros2", "run", "demo_nodes_cpp", "listener"]
          ports:
            - containerPort: {{ .Values.containerPort }}
        - name: load-generator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python3", "/scripts/{{ .Values.loadGenerator.scriptPath }}"]
          env:
            - name: MESSAGE_RATE
              value: "{{ .Values.loadGenerator.messageRate }}"
          volumeMounts:
            - name: load-sim
              mountPath: /scripts/{{ .Values.loadGenerator.scriptPath }}
              subPath: {{ .Values.loadGenerator.scriptPath }}
      volumes:
        - name: load-sim
          configMap:
            name: {{ include "ros2-microservices.fullname" . }}-load-sim
