apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ros2-microservices.fullname" . }}-load-sim
data:
  {{ .Values.loadGenerator.scriptPath }}: |
    #!/usr/bin/env python3
    import os
    import time
    import rclpy
    from rclpy.node import Node
    from std_msgs.msg import String

    class LoadGenerator(Node):
        def __init__(self):
            super().__init__('load_generator')
            self.pub = self.create_publisher(String, 'load_topic', 10)
            self.rate_hz = float(os.getenv('MESSAGE_RATE', '1'))
            self.timer = self.create_timer(1.0 / self.rate_hz, self.publish_message)

        def publish_message(self):
            msg = String()
            msg.data = 'Load at %f' % self.get_clock().now().seconds_nanoseconds()[0]
            self.pub.publish(msg)
            self.get_logger().info(f'Published: "{msg.data}"')

    def main():
        rclpy.init()
        node = LoadGenerator()
        try:
            rclpy.spin(node)
        except KeyboardInterrupt:
            pass
        finally:
            node.destroy_node()
            rclpy.shutdown()

    if __name__ == '__main__':
        main()
