apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ros2-microservices.fullname" . }}-load-generator
  labels:
    {{- include "ros2-microservices.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.metrics.port }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
        - name: load-generator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /ros_entrypoint.sh
            - python3
            - /scripts/{{ .Values.loadGenerator.scriptPath }}
          env:
            - name: MESSAGE_RATE
              value: "{{ .Values.loadGenerator.messageRate }}"
            - name: METRICS_PORT
              value: "{{ .Values.metrics.port }}"
          ports:
            - containerPort: {{ .Values.metrics.port }}
          volumeMounts:
            - name: load-sim
              mountPath: /scripts/{{ .Values.loadGenerator.scriptPath }}
              subPath: {{ .Values.loadGenerator.scriptPath }}
      volumes:
        - name: load-sim
          configMap:
            name: {{ include "ros2-microservices.fullname" . }}-load-sim